/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DateNumber {
        "max"?: number;
        "min"?: number;
        "name": string;
        "value"?: string;
    }
    interface DateParent {
        "value"?: string;
    }
}
declare global {
    interface HTMLDateNumberElement extends Components.DateNumber, HTMLStencilElement {
    }
    var HTMLDateNumberElement: {
        prototype: HTMLDateNumberElement;
        new (): HTMLDateNumberElement;
    };
    interface HTMLDateParentElement extends Components.DateParent, HTMLStencilElement {
    }
    var HTMLDateParentElement: {
        prototype: HTMLDateParentElement;
        new (): HTMLDateParentElement;
    };
    interface HTMLElementTagNameMap {
        "date-number": HTMLDateNumberElement;
        "date-parent": HTMLDateParentElement;
    }
}
declare namespace LocalJSX {
    interface DateNumber {
        "max"?: number;
        "min"?: number;
        "name"?: string;
        "onUpdateValue"?: (event: CustomEvent<string[]>) => void;
        "value"?: string;
    }
    interface DateParent {
        "onUpdateDate"?: (event: CustomEvent<string>) => void;
        "value"?: string;
    }
    interface IntrinsicElements {
        "date-number": DateNumber;
        "date-parent": DateParent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "date-number": LocalJSX.DateNumber & JSXBase.HTMLAttributes<HTMLDateNumberElement>;
            "date-parent": LocalJSX.DateParent & JSXBase.HTMLAttributes<HTMLDateParentElement>;
        }
    }
}
